### ISSUE TITLE
Is vault-secrets-operator supported on older k8s version?

### ISSUE THREAD

**Issue by prakharrr-sl** [ricoberger/vault-secrets-operator#101]
Hi @ricoberger,
Sorry I couldn't find a supported versions list. I wanted to try VSO on an older version of k8s cluster. Do you know if this would work in 1.10.x ?

**Comment by ricoberger** [comment]
Hi @prakharrr-sl, no the operator isn't working with this version. The operator uses the `apiextensions.k8s.io/v1` API for the CRD, which was introduced in v1.16. This should also be the oldest version which is supported right now.

**Comment by prakharrr-sl** [comment]
@ricoberger Gotcha!
Thanks for your prompt response!
