### ISSUE TITLE
Access based on vault policies

### ISSUE THREAD

**Issue by anuragpulla** [ricoberger/vault-secrets-operator#103]
Hello,

Is there a way we can have access control with the kubernetes auth method similar to how the [vault agent injector](https://github.com/hashicorp/vault-k8s)  has? For instance, it fetches the secret only if you/(serviceaccount) are authorized to read the secrets from a a given path in vault.

I see the option for using vaultRole but looking for a way for it to restrict using a certain role say "admin" which can get any secret from vault.

If that is not possible, is there a way we can have multiple instances of this operator configured with different roles/policies ?

**Comment by ricoberger** [comment]
Hi @anuragpulla, during the setup you can specify the Vault Role, which should be used by the operator:

```sh
vault auth enable kubernetes

# Tell Vault how to communicate with the Kubernetes cluster
vault write auth/kubernetes/config \
  token_reviewer_jwt="$SA_JWT_TOKEN" \
  kubernetes_host="$K8S_HOST" \
  kubernetes_ca_cert="$SA_CA_CRT"

# Create a role named, 'vault-secrets-operator' to map Kubernetes Service Account to Vault policies and default token TTL
vault write auth/kubernetes/role/vault-secrets-operator \
  bound_service_account_names="vault-secrets-operator" \
  bound_service_account_namespaces="$VAULT_SECRETS_OPERATOR_NAMESPACE" \
  policies=vault-secrets-operator \
  ttl=24h
```

You can also run multiple instances of the operator. Each operator will then use his own ServiceAccount with it's configured Vault Role. When you run multiple instance of the operator you can also restrict the namespaces, which should be managed by an instance of the operator via the [`vault.namespaces`](https://github.com/ricoberger/vault-secrets-operator/blob/4df8e2c4e7fb5ea4cfeaee2f30650adac46af4ae/charts/vault-secrets-operator/values.yaml#L88) value in the Helm chart.

Does this help you?

**Comment by anuragpulla** [comment]
Yes this definitely helps, thank you so much for the details. :)
