### ISSUE TITLE
Cannot renew token after a period of time using kubernetes auth

### ISSUE THREAD

**Issue by ryneal** [ricoberger/vault-secrets-operator#105]
I'm experiencing a scenario using kubernetes auth where (for reasons I'm yet to understand) the token renewal is failing after a number of successful attempts

The logs are below (vault URL ommitted);

```
vault-secrets-operator 2021-05-12T05:26:45.586Z    INFO controller-runtime.manager starting metrics server {"path": "/metrics"}
vault-secrets-operator 2021-05-12T05:29:14.238Z    INFO vault Renew Vault token
vault-secrets-operator 2021-05-12T05:31:44.264Z    INFO vault Renew Vault token
vault-secrets-operator 2021-05-12T05:34:14.285Z    INFO vault Renew Vault token
vault-secrets-operator 2021-05-12T05:36:44.320Z    INFO vault Renew Vault token
vault-secrets-operator 2021-05-12T05:39:14.350Z    INFO vault Renew Vault token
vault-secrets-operator 2021-05-12T05:41:44.369Z    INFO vault Renew Vault token
vault-secrets-operator 2021-05-12T05:41:44.384Z    ERROR vault Could not renew token {"error": "Error making API request.\n\nURL: PUT <vault_url>:8200/v1/auth/token/renew-self\nCode: 403. Errors:\n\n* permission denied"}vault-secrets-operatorgithub.com/go-logr/zapr.(*zapLogger).Errorvault-secrets-operator    /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
vault-secrets-operator github.com/ricoberger/vault-secrets-operator/vault.(*Client).RenewTokenvault-secrets-operator    /workspace/vault/client.go:69
vault-secrets-operator 2021-05-12T05:41:44.385Z    INFO vault Token information: (*api.Secret)(nil) {"error": "Error making API request.\n\nURL: GET <vault_url>/v1/auth/token/lookup-self\nCode: 403. Errors:\n\n* permission denied"}
```

I have the following environment variables set;

```
VAULT_ADDRESS | <vault_url> |  
VAULT_APP_ROLE_PATH | auth/approle |  
VAULT_AUTH_METHOD | kubernetes |  
VAULT_KUBERNETES_PATH | auth/kubernetes |  
VAULT_KUBERNETES_ROLE | internal-app |  
VAULT_RECONCILIATION_TIME | 0 |  
VAULT_TOKEN_LEASE_DURATION | 300 |  
VAULT_TOKEN_MAX_TTL | 600 |  
VAULT_TOKEN_PATH |   |  
VAULT_TOKEN_RENEWAL_INTERVAL | 150 |  
VAULT_TOKEN_RENEWAL_RETRY_INTERVAL | 30 |  
WATCH_NAMESPACE
```

Lease & Max TTL are set as vault defaults currently. As my renewal is every 2.5 minutes, I'm seeing successful token renewal for 15 minutes then it starts failing.

Restarting the pod resolves the issue, but I cannot rely on this as it is a manual process.

Any assistance on this would be appreciated!

Some proposals I see to resolve the issue;

- Have an environment variable which would force fresh token acquisition after a period of time
- Have the pod health endpoint report unhealthy in this scenario to trigger a pod restart

**Comment by ricoberger** [comment]
Hi @ryneal, does the operator log any errors, when the renewal stops working after 15 minutes.

I think checking, if the renewal of tokens failed to often within the liveness probe endpoint, would be a good idea. I will look into this asap.

**Comment by ryneal** [comment]
@ricoberger the only errors I can see are the ones included above

I seem to have it operating more stable now by ensuring the following;

- The role has Max generated tokens set to '0' (unlimited). I believe there's a bug in Vault here as I had not set it on creation and it was still presented as zero.
- Use default TTL and max TTL rather than setting it (max TTL was set on the role to 900 seconds, which I think is what was driving the 15 minutes behviour I was seeing)
- Ensure visibility listing for the role was set to 'unauth' - im not sure if this actually makes a difference, but this is my configuration and it seems to be working

I have a suspicion I may hit the same issue again once the default Max TTL (32 days) is hit, so the fix you agreed above seems like a safe option to ensure full recovery without manual intervention - it would also make sense so we can enforce stronger security settings on our roles

**Comment by ricoberger** [comment]
I published a new release [1.14.5](https://github.com/ricoberger/vault-secrets-operator/releases/tag/1.14.5), were the liveness probe will fail, when the renewal of the Vault token failed 10 times.

**Comment by ryneal** [comment]
thank you @ricoberger, I will deploy this latest release

Would it worth considering for future iterations that the failed threshold can be set by an environment variable?

**Comment by ricoberger** [comment]
Yes, this shouldn't be a problem.
