### ISSUE TITLE
Helm upgrade from 1.14.5 to 1.15.0 deleted the CRD

### ISSUE THREAD

**Issue by ChipWolf** [ricoberger/vault-secrets-operator#115]
I don't immediately see why, but the helm upgrade from 1.14.5 to 1.15.0 deleted the VaultSecret CRD.
I downgraded to 1.14.5, the CRD reappears; on upgrade, it disappears again.

**Comment by ricoberger** [comment]
Hi @ChipWolf, we had a breaking change in the Helm chart for version 1.15.0 to follow the best practice for CRDs which is recommended in the Helm documentation (#111).

You can uninstall and then install the Helm chart to have the CRD with version 1.15.0.

Another option would to the delete the corresponding Helm secrets, deleting all resources for the Helm chart except the CRD and reinstalling the chart with the new version:

```
k create namespace vault-secrets-operator

helm install vault-secrets-operator ricoberger/vault-secrets-operator --namespace=vault-secrets-operator --version=1.14.5

k -n vault-secrets-operator delete secret -l name=vault-secrets-operator,owner=helm

k delete namespace vault-secrets-operator
k delete clusterrole vault-secrets-operator
k delete clusterrolebinding vault-secrets-operator

helm install vault-secrets-operator ricoberger/vault-secrets-operator --namespace=vault-secrets-operator --version=1.15.0
```

**Comment by avbasov** [comment]
If CRD is gone, all vaultsecrets are deleted automatically. Loosing existed vaultsecrets is an unacceptable situation for me. So, there is the third kinda hacky way. You can actually make Helm think that CRD wasn't installed by it. For that you need to modify Helm secret that contains information about the last installed vault-secrets-operator release.

**Comment by ricoberger** [comment]
I would close the issue if this is ok for everyone. Sorry for the breaking change again 😞
