### ISSUE TITLE
Applications error

### ISSUE THREAD

**Issue by f0rcas** [ricoberger/vault-secrets-operator#133]
Hi. 
I get errors and POD restart. Number of replicas 1, authMethod: kubernetes, reconciliationTime: 0. The application restarts constantly, but secrets create normaly.
`E1126 03:10:39.646091       1 leaderelection.go:367] Failed to update lock: Put "https://10.57.0.1:443/api/v1/namespaces/vault/configmaps/vaultsecretsoperator.ricoberger.de": context deadline exceeded
I1126 03:10:39.646152       1 leaderelection.go:283] failed to renew lease vault/vaultsecretsoperator.ricoberger.de: timed out waiting for the condition
{"level":"error","ts":1637896239.6461787,"logger":"setup","msg":"problem running manager","error":"leader election lost"}`

**Comment by ricoberger** [comment]
Hi @f0rcas, I we had some similar issues with some operators in the past. I think the problem might be your Kubernetes API and not the operator.

I published a new version [1.16.1](https://github.com/ricoberger/vault-secrets-operator/releases/tag/1.16.1), which allows to modify the arguments of the operator.

You can try to set the following args in the Helm chart, to disable the leader election, which shouldn't be a problem as long as you are running the operator with replicas 1:

```yaml
args:
  - -leader-elect=false
```

**Comment by f0rcas** [comment]
tnx. this solved my problem.

**Comment by ricoberger** [comment]
Nice. I would close the issue then.
