### ISSUE TITLE
Not pull image 1.16.1

### ISSUE THREAD

**Issue by ymrsmns** [ricoberger/vault-secrets-operator#135]
Hi

The specified image was not found in hub.docker.io

```
docker pull docker.io/ricoberger/vault-secrets-operator:1.16.1
Error response from daemon: manifest for ricoberger/vault-secrets-operator:1.16.1 not found: manifest unknown: manifest unknown
```

https://github.com/ricoberger/vault-secrets-operator/blob/master/charts/vault-secrets-operator/values.yaml#L6

**Comment by ricoberger** [comment]
Hi @ymrsmns the image should now be available at Docker Hub.

It always takes up to 1 hour before the image is build and pushed to Docker Hub after a new release.
