### ISSUE TITLE
Update documentation for reconciliationTime

### ISSUE THREAD

**Issue by darrencola-dev** [ricoberger/vault-secrets-operator#147]
It is not clear whether the time is in seconds or minutes. Could we add to the documentation exactly what the number represents?  

Thanks!

**Comment by ricoberger** [comment]
Hi @darrencola-dev thanks for your suggestions. You are right the documentation around some of the options are not in a good shape.

I tried to add some clarification for the `vault. reconciliationTime` / `VAULT_RECONCILIATION_TIME` values. Please let me know if you found some other places were we could improve our documentation.
