### ISSUE TITLE
Error with vault-secrets-operator

### ISSUE THREAD

**Issue by jvaitla** [ricoberger/vault-secrets-operator#150]
Hi 
Having issues with vault-secrets-operator in some clusters, what need to done to fix this issue?

Here was one of the error 

E0223 16:52:57.962534       1 leaderelection.go:330] error retrieving resource lock flux-system/vaultsecretsoperator.ricoberger.de: etcdserver: request timed out

**Comment by ricoberger** [comment]
Hi @jvaitla, I think this looks like a problem with your Kubernetes API server. If you see this very often you can disable the leader election of the operator via

```yaml
args:
  - -leader-elect=false
```

**Comment by ricoberger** [comment]
Since there was no reply yet, I would close the issue for now. If you still have problems please let me know.
