### ISSUE TITLE
Way to monitor failed VaultSecrets sync

### ISSUE THREAD

**Issue by fbueno** [ricoberger/vault-secrets-operator#154]
Sometimes people may add a `VaultSecret` that has a wrong `path`. 
In such case, secret won't be created/synced.

Is there a way to export such status to prometheus endpoint `/metrics`?

**Comment by ricoberger** [comment]
Hi @fbueno, the `/metrics` endpoint on port `8080` exposes the following counter metrics

```
controller_runtime_reconcile_total{controller="vaultsecret",result="error"} 13
controller_runtime_reconcile_total{controller="vaultsecret",result="requeue"} 0
controller_runtime_reconcile_total{controller="vaultsecret",result="requeue_after"} 44306
controller_runtime_reconcile_total{controller="vaultsecret",result="success"} 0
```

It should be possible to use the `controller_runtime_reconcile_total{controller="vaultsecret",result="error"}` metric to monitor failed reconciliations.

Does this already help or are you looking for a more detailed metric, which also contains the name / namespace of the reconciled VaultSecret?

**Comment by fbueno** [comment]
@ricoberger That can help, indeed. 
Thank you. 
Maybe if we had a more verbose metric it could help even more.
But for me it does help. Thank you again.

**Comment by ricoberger** [comment]
Hi @fbueno, I added a new metric `vaultsecrets_reconciliations_total` which indicates reconciliation failures per VaultSecret. 

With this you can create an alert like `sum(rate(vaultsecrets_reconciliations_total{status="False"}[5m])) by (namespace, name)` to get notified in case of a problem and then check the VaultSecret CR to get the detailed error.

I would close this issue for now, if you have any further suggestion feel free to reopen the issue.
