### ISSUE TITLE
missing secret vault-secrets-operator or bad path in volume

### ISSUE THREAD

**Issue by Forest-fox** [ricoberger/vault-secrets-operator#157]
Image version 1.18
Kubernetes 1.21
Used manual install from yaml configuration with variables:
VAULT_AUTH_METHOD : kubernetes
VAULT_AUTH_PATH : auth/k8s-testing
VAULT_KUBERNETES_ROLE : vault-secrets-operator

In Vault i have configured method kubernetes on that path with that role.
When container starts it spam error "missing secret vault-secrets-operator or bad path in volume". Network traffic flow between Vault and node OK.

If i delete ROLE variable - error switch to "shared client not initialized and vaultRole property missing".

**Comment by ricoberger** [comment]
Hi @Forest-fox, the error message `missing secret vault-secrets-operator or bad path in volume` can be ignored for the Kubernetes auth method.

Did you also create a ServiceAccount `vault-secrets-operator` and added it to the Deployment like here https://github.com/ricoberger/vault-secrets-operator/blob/075157d1af6b924d8507fc1ef18b8689d5e6dcfb/charts/vault-secrets-operator/templates/deployment.yaml#L34

**Comment by Forest-fox** [comment]
Thanks for answer. Issue was related to wrong configuration parameters in vault.
