### ISSUE TITLE
Future of the project

### ISSUE THREAD

**Issue by Pluggi** [ricoberger/vault-secrets-operator#193]
Hashicorp announced their own Vault Secrets Operator in March : https://www.hashicorp.com/blog/vault-secrets-operator-a-new-method-for-kubernetes-integration

What is the future of the project? Do you plan to keep updating it or will you retire it once they ship their v1?

**Comment by ricoberger** [comment]
Hi @Pluggi, we have no plans to deprecate the operator. We will continue maintaining it and ensure that it is working with the latest Kubernetes and Vault versions.

Currently there are no plans for new features, but if anyone wants to contribute a new feature we are open for pull requests.

I hope this helps, if not please let me know.

**Comment by Pluggi** [comment]
Sounds great, thanks a lot!
