### ISSUE TITLE
consider leveraging vault native kubernetes auth instead of token

### ISSUE THREAD

**Issue by billimek** [ricoberger/vault-secrets-operator#2]
It appears that the solution currently relies on directly communicating with the vault server using a long-lived token.

It may be worth considering adopting the [vault kubernetes auth method](https://www.vaultproject.io/docs/auth/kubernetes.html) as an approach for the vault secrets operator to authenticate to vault instead via a service account.

**Comment by ricoberger** [comment]
Hi and thanks for your interest in the Vault Secrets Operator. This is definitely one of the next topics I will look at.
