### ISSUE TITLE
Restrict the controller to a particular namespace

### ISSUE THREAD

**Issue by rtluckie** [ricoberger/vault-secrets-operator#20]
It would be awesome if `vault-secret-operator`'s controller could be restricted to a particular k8s namespace (or include, exclude spec).

Similar to https://github.com/tuenti/secrets-manager/pull/39

**Comment by ricoberger** [comment]
Hi, thanks for your request.

After a first look I would upgrade the operator to use the operator-sdk [v0.11.x](https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md#v011x) before implementing your request.

The new version bumps the underlying controller-runtime version to v0.2.0, which introduces a new feature to watch a list of namespaces (see https://github.com/operator-framework/operator-sdk/pull/1512).

**Comment by ricoberger** [comment]
Hi, I updated the operator-sdk to v0.11.x and added the possibility to set the namespaces the operator should watch. There is also a new value `vault.namespaces` in the Helm chart, which accepts a comma separated list of namespaces.

- https://github.com/ricoberger/vault-secrets-operator/commit/8f8cba8d485139a2154f25af60d82c7ca0d23ebb
- https://github.com/ricoberger/vault-secrets-operator/commit/cc88c70fc8de838b019d2d5319575247e9a254de

The feature is included in version [1.4.0](https://github.com/ricoberger/vault-secrets-operator/releases/tag/1.4.0).

@rtluckie if you are ok with this I would close this issue.

**Comment by rtluckie** [comment]
@ricoberger changes LGTM.  Thank you very much for being to responsive!  I will let you know if I run into any issues during testing.

**Comment by Kampe** [comment]
If a user doesn't present a value for `WATCH_NAMESPACE` what behavior can we expect?  Will it have the ability to create vault secrets in all namespaces?

**Comment by ricoberger** [comment]
Hi @Kampe, when `WATCH_NAMESPACE` is set to `""` all namespaces will be watched. The list of namespaces can be restricted with a value like `ns1,ns2,ns3`.

When the `WATCH_NAMESPACE` environment variable isn't set the operator would not start.
