### ISSUE TITLE
Exclude given VaultSecrets

### ISSUE THREAD

**Issue by ejsuncy** [ricoberger/vault-secrets-operator#234]
Is it possible to have a VSO deployment target a subset of VaultSecrets? 

My use case is: I have secrets in two different vault namespaces. I created two VSO deployments in the same kubernetes namespace. One VSO deployment should reconcile only the VaultSecrets that are in the vault namespace it is configured for. Currently, each VSO deployment tries to reconcile all VaultSecrets.

**Comment by ricoberger** [comment]
Hi @ejsuncy this is not possible, the operator can only be restricted to a list of namespaces. A possible solution could be to add a new configuration property, so that the operator ignores secrets which are not within the configured namespace.

A user would then have to set the `VAULT_NAMESPACE` environment variable and the `vaultNamespace` property on the secret. If they are the same the secret would be reconciled if they are different the secret is ignored. The only disadvantage would then be, that nested namespaces are not allowed anymore.

Would this be a possible solution for you?

**Comment by ejsuncy** [comment]
Hi @ricoberger, thanks for the response. yes, what you propose would be a great solution. Looking through the CRD for `VaultSecret`, I saw `vaultNamespace` and had assumed that was the behavior. I didn't realize nested namespaces were supported. 

Adding the configuration option you suggest would be great!

**Comment by ricoberger** [comment]
Hi @ejsuncy, I finally had some time to implement this feature. Please let me know if it is working as expected or if there are things which must be changed.

**Comment by ejsuncy** [comment]
@ricoberger Thanks! I'll roll this out and test it.

**Comment by ejsuncy** [comment]
@ricoberger I'm not sure if this is an issue on my side or on the VSO side. With the VaultSecret `spec.vaultNamespace` field set, I see the other instance logging a statement about ignoring the secret as expected, but the instance that is responsible for this vault secret (where the `VAULT_RESTRICT_NAMESPACE`  = `true`, and the VaultSecret `spec.vaultNamespace` matches the instance's `VAULT_NAMESPACE` variable) is showing error logs like this:

```
message: "Error making API request.\n\nNamespace: my_namespace/my_namespace\nURL:
 35       GET https://my-vault-address.domain/v1/sys/internal/ui/mounts/my_mount/my/path/to/secret\nCode:
 36       403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"

```

I've verified that my vault policy is allowing read permissions on my secrets under `my_mount/*`, I've double checked my role id and secret id variables.

Is it still trying to use nested namespaces? the `Namespace: my_namespace/my_namespace` looks suspicious.

**Comment by ejsuncy** [comment]
@ricoberger It looks like [this piece of code](https://github.com/ricoberger/vault-secrets-operator/blob/5a70aae9bd9f8fa4a18d1c5a90c3d7776e11e702/vault/client.go#L126) may also need to have its logic updated so that if the `VaultSecret.vaultNamespace` is not empty, but is the same as the `VAULT_NAMESPACE` var and `VAULT_RESTRICT_NAMESPACE` is set to true, do not concat the root namespace with the `VaultSecret.vaultNamespace`.

**Comment by ricoberger** [comment]
Hi @ejsuncy, thanks for testing and the feedback. I published a new version 1.24.1, which should fix the issue.

**Comment by ejsuncy** [comment]
Thanks for implementing the fix and for the quick turnaround and responsiveness!

**Comment by ejsuncy** [comment]
@ricoberger I deployed and tested 1.24.1, and the issue is fixed. Thanks for adding such a great feature!
