### ISSUE TITLE
[Feature request] Allow communication with vault using custom TLS certs

### ISSUE THREAD

**Issue by grzegdl** [ricoberger/vault-secrets-operator#27]
It's a good security practice to restrict communication with Vault to https and only with previously generated TLS keys. Especially when dealing with Vault deployed externally (outside the cluster with Vault Secrets Operator).

**Comment by ricoberger** [comment]
Hi @grzegdl, thanks for your feature requests. This sounds like a useful addition. I will take a look into the implementation during this week.

My idea would be to pass the certificate via a mounted volume from a secret to the pod. Then we can check if the certificate is present and pass it to the underlying HTTP client of the Vault client.

Do you have any further recommendations?

**Comment by grzegdl** [comment]
Passing it as a secret will definitely be a good approach. I would see it as:
1. For simplicity using same/similar variables as in Vault Agent - https://www.vaultproject.io/docs/agent/index.html#vault-stanza
2. Making it work via a global switch like TLS_SECRET = ""
- if empty then no certs being loaded
- if we state a secret name then all needed settings i.e. VAULT_CACERT, VAULT_CLIENT_CERT should be taken from the secret
3. For security purposes secret should be deployed separately before (outside the helm chart)

**Comment by ricoberger** [comment]
Hi @grzegdl, first of all thanks for your input.

If you want, you may like to check out the following PR #28.

**Comment by grzegdl** [comment]
Thank you!
