### ISSUE TITLE
How to Change the Log Level?

### ISSUE THREAD

**Issue by Zernov-A** [ricoberger/vault-secrets-operator#291]
I am currently using the vault-secrets-operator, and I would like to reduce the number of logs being generated by changing the log level to error or a less verbose level.

I couldn't find clear documentation on how to configure the log level. By default, the logs seem to be at the info level, and they are quite verbose.

Is there support for changing the log level via environment variables or other methods?

**Comment by ricoberger** [comment]
Hi @Zernov-A, the logging behavior can be configured via the following arguments:

```
  -zap-devel
        Development Mode defaults(encoder=consoleEncoder,logLevel=Debug,stackTraceLevel=Warn). Production Mode defaults(encoder=jsonEncoder,logLevel=Info,stackTraceLevel=Error)
  -zap-encoder value
        Zap log encoding (one of 'json' or 'console')
  -zap-log-level value
        Zap Level to configure the verbosity of logging. Can be one of 'debug', 'info', 'error', or any integer value > 0 which corresponds to custom debug levels of increasing verbosity
  -zap-stacktrace-level value
        Zap Level at and above which stacktraces are captured (one of 'info', 'error', 'panic').
  -zap-time-encoding value
        Zap time encoding (one of 'epoch', 'millis', 'nano', 'iso8601', 'rfc3339' or 'rfc3339nano'). Defaults to 'epoch'.
```

If you are using the Helm chart, sth. like the following should reduce the logs:

```yaml
args:
  - -leader-elect
  - -zap-log-level=error
```

**Comment by Zernov-A** [comment]
Hi @ricoberger!
Thank you for your reply and detailed explanation!
This information is very helpful and works for me.
