### ISSUE TITLE
Is it possible to import existing kubernetes secrets into vault? 

### ISSUE THREAD

**Issue by kungfuchicken** [ricoberger/vault-secrets-operator#52]
The examples in the readme show how to create a VaultSecret that pushes existing secrets in Vault into k8s, but the diagram has arrows going both ways. Is it possible to to upload an existing k8s secret into Vault?

**Comment by ricoberger** [comment]
Hi @kungfuchicken, no this is not possible. At the moment the operator only syncs secrets from Vault to Kubernetes. Changes made to the Kubernetes Secret are not synced back to Vault.

**Comment by ricoberger** [comment]
I would close this issue, since syncing Kubernetes secrets back to Vault is out of scope for the operator.

If you have any further questions feel free to reopen the issue or to open a new one.
