### ISSUE TITLE
Created secrets missing ownerReferences metadata

### ISSUE THREAD

**Issue by rra** [ricoberger/vault-secrets-operator#59]
Since upgrading to vault-secrets-operator 1.10.0 from 1.9.0, vault-secrets-operator is no longer setting the `ownerReferences` metadata on the secrets it creates.

We use Argo CD for Git ops on Kubernetes clusters, and it relies on this metadata to know that the `Secret` is derived from the `VaultSecret` and therefore is an expected resource. Without this metadata, the secrets all show up as stray resources that need pruning.

(Thank you very much for maintaining this software. We use it heavily!)

**Comment by ricoberger** [comment]
Hi @rra, sorry I think I forget that during the migration to the new Operator SDK version.

This should be fixed in version [1.10.1](https://github.com/ricoberger/vault-secrets-operator/releases/tag/1.10.1).

**Comment by rra** [comment]
Wow, thank you for the incredibly fast fix! I've deployed the new version and confirmed that it fixes the problem.
