### ISSUE TITLE
Any plans to support Vault KV Secrets Engine - Version 2? 

### ISSUE THREAD

**Issue by cristian-radu** [ricoberger/vault-secrets-operator#6]
With version 2 of the kv secrets engine, Vault can store multiple versions of the same secret. The controller could then reference a specific version via the CRD spec and this would provide a means to reflect the fact that the secret value has been modified as a git commit. 

Any thoughts on this?

**Comment by AndresPineros** [comment]
I'm not completely sure but I think I've read the Go SDK for Vault and it doesn't support KV version 2.

The issue goes beyond this operator.

**Comment by ricoberger** [comment]
After a first test I can get a kv2 secret:

```
&api.Secret{RequestID:\"e5dc1ecc-7d96-1026-6f7c-4cdcceabeb89\", LeaseID:\"\", LeaseDuration:0, Renewable:false, Data:map[string]interface {}{\"data\":map[string]interface {}{\"hello\":\"world\"}, \"metadata\":map[string]interface {}{\"created_time\":\"2019-09-03T16:18:35.434460886Z\", \"deletion_time\":\"\", \"destroyed\":false, \"version\":\"3\"}}, Warnings:[]string(nil), Auth:(*api.SecretAuth)(nil), WrapInfo:(*api.SecretWrapInfo)(nil)}
```

The returned structure is a little bit different then the one for a kv1 secret, but I think it should be possible. I will try to implement a useful version.

If it works, I would also change the CRD to include a new field called `secretsEngine` or sth. like this. The field should be optional, to not introduce a breaking change.

**Comment by cristian-radu** [comment]
Was just about to comment. Seems the KV store must have versioning enabled (obviously), and then we could make requests like https://www.vaultproject.io/api/secret/kv/kv-v2.html#read-secret-version using https://github.com/hashicorp/vault/blob/master/api/logical.go#L53

**Comment by ricoberger** [comment]
@cristian-radu thanks for the links.

Since it seems it is also possible to specify the version of the secret which should be used. What do you think should this also be included or should the Operator use only the latest version?

**Comment by cristian-radu** [comment]
@ricoberger I was thinking we could allow specifying the secret version to be used as well as part of the CRD spec. That way when you push a new version of the secret to Vault, the only way to actually deploy this new secret to Kubernetes would be to make a commit in git that references the new version. 

So you "drive" the actual change to he Kubernetes secret from git.

**Comment by ricoberger** [comment]
Thanks again for the links. Was then implemented faster than expected. I will update the readme and Helm chart and release a new version of the Operator.
