### ISSUE TITLE
Support for approle auth method for Vault

### ISSUE THREAD

**Issue by pbchekin** [ricoberger/vault-secrets-operator#79]
It would be nice to support approle auth method for Vault:
https://www.vaultproject.io/docs/auth/approle

It will require adding an additional `authMethod` `approle`. Also the following settings are needed:
* `VAULT_ROLE_ID`
* `VAULT_SECRET_ID`
* `VAULT_APP_ROLE_PATH`
* `VAULT_TOKEN_MAX_TTL` - a Vault token returned by the approle auth method  has a maximum TTL (usually 30 days), so we can renew the issued token only during the specified time frame. After that we need to re-authenticate with `VAULT_ROLE_ID` and `VAULT_SECRET_ID` and receive a new token.

@ricoberger if you are OK with the feature I can make a PR for that.

**Comment by ricoberger** [comment]
Hi @pbchekin, this sounds like a useful addition for the operator. Feel free to create a PR for this 🙂.

**Comment by swarren83** [comment]
@pbchekin I am interested in being able to use this auth method as well.  Let me know how I can help.

**Comment by pbchekin** [comment]
@ricoberger, I've created #82 for this feature.
@swarren83 I think you can help with reviewing and testing the PR.

In my environment, I've tested that there are no regressions for `token` auth method and tested that the new `approle` works as expected. To test that the new code works and requests a new token, I've created AppRole that creates shot living tokens like this:

```
vault write auth/approle/role/vault-secrets-operator \
  token_policies=vault-secrets-operator \
  secret_id_ttl=0 \
  token_ttl=10m \
  token_max_ttl=10m \
  token_explicit_max_ttl=10m \
  token_period=10m
```

**Comment by ricoberger** [comment]
New version [1.13.0](https://github.com/ricoberger/vault-secrets-operator/releases/tag/1.13.0) includes the mentioned PR.

Thank you for your contribution 🙂
