### ISSUE TITLE
No status in VaultSecret resource

### ISSUE THREAD

**Issue by swarren83** [ricoberger/vault-secrets-operator#80]
@ricoberger Would it be possible to add a status section to the VaultSecret resource when described?  Status field could show one of the following:

- Pending
- Success
- Failed
- Unknown

Failed would mean that the k8s secret failed to be created.

This can be added to [`VaultSecretStatus` struct](https://github.com/ricoberger/vault-secrets-operator/blob/1807db03f2abddb506b60e6c2a90c367a5505ef8/api/v1alpha1/vaultsecret_types.go#L61).

```
kubectl -n NAMESPACE describe vaultsecret.ricoberger.de testing
Name:         testing
Namespace:    NAMESPACE
Labels:       app.kubernetes.io/instance=foo
-->Status: Success
Annotations:  <none>
API Version:  ricoberger.de/v1alpha1
Kind:         VaultSecret
Metadata:
  Creation Timestamp:  2021-02-08T22:10:28Z
  Generation:          2
  Resource Version:    1234567890
  Self Link:           /apis/ricoberger.de/v1alpha1/namespaces/NAMESPACE/vaultsecrets/testing
  UID:                 1234556890-123908-1293081203-12312098
Spec:
  Path:             kv/foo/bar/test
  Type:             Opaque
  Vault Namespace:  VAULT_NAMESPACE
Events:             <none>
```

I can work on submitting a PR for this.

**Comment by ricoberger** [comment]
Hi @swarren83, sounds like a useful addition. If you want to create a PR you are welcome.

Maybe it can also contain the error message, when the status is set to failed.

**Comment by ricoberger** [comment]
Hi @swarren83, did you started working on this?

If not a can have a look at this in the next day.

**Comment by swarren83** [comment]
@ricoberger No, I have been unable to start work on this feature.  If you get to it before I do, I can help test it.

**Comment by ricoberger** [comment]
Hi @swarren83, if you want, you can check out #90 for this feature.

```
NAME   CREATED   REASON   MESSAGE   LAST TRANSITION   AGE
test   False     FetchFailed   secret is nil        2021-03-14T18:51:47Z   2021-03-14T18:39:51Z
test   True      Updated       Secret was updated   2021-03-14T18:52:54Z   2021-03-14T18:39:51Z
```

**Comment by swarren83** [comment]
@ricoberger Thank you for taking care of this feature.  It looks great!
