### ISSUE TITLE
Support Nested Secret Values

### ISSUE THREAD

**Issue by rtluckie** [ricoberger/vault-secrets-operator#9]
I am looking to use the vault-secrets-operator to support secrets in [flux](https://docs.fluxcd.io/projects/helm-operator/en/latest/references/helmrelease-custom-resource.html?#secrets).

Secrets with nesting don't seem to work.  
```
{
  "values.yaml": {
    "postgres": {
      "superuserPassword": "secret",
      "replicationPassword": "secret"
    }
  }
}
```
In vault the secret looks like this;
```
======= Data =======
Key            Value
---            -----
values.yaml    map[postgres:map[replicationPassword:secret superuserPassword:secret]]
```

**Comment by ricoberger** [comment]
Hi, thanks for open the issue. I was able to reproduce this with `cat values.json | vault kv put kv2/nested-secret -`. Then the value for the `values.yaml` key is of the type `map[string]interface {}`, which could not be parsed by the operator.

For using the Vault Secrets Operator with Flux you can create the Vault secrets with the following command for now:

```
cat <<EOF | vault kv put kv2/nested-secret values.yaml=-
{
  "postgres": {
    "superuserPassword": "secret",
    "replicationPassword": "secret"
  }
}
EOF
```

Then the value of the `values.yaml` key is of the type `string`, which could be parsed by the operator.

I will try to find a good way to handle nested secret values.

**Comment by ricoberger** [comment]
#10 should resolve this issue. If any other case does not work, please do not hesitate to create a new issue.
