### ISSUE TITLE
Support ARM

### ISSUE THREAD

**Issue by ChipWolf** [ricoberger/vault-secrets-operator#92]
Could you please build the containers for arm/arm64 as vault-k8s [now supports arm](https://github.com/hashicorp/vault-k8s/issues/64#issuecomment-802381296)

**Comment by ricoberger** [comment]
Hi @ChipWolf, I do not have an arm system at the moment. Can you test, if the `ricoberger/vault-secrets-operator:dev` image works on arm?

**Comment by ChipWolf** [comment]
Hi @ricoberger doesn't seem to work yet, the app is still expecting amd64.
https://github.com/ricoberger/vault-secrets-operator/blob/add-arm-support/Dockerfile#L19

Probably the GOARCH? I can provide you with a fresh cloud instance with arm64 for testing if required.

**Comment by ChipWolf** [comment]
Checking the [latest build](https://github.com/ricoberger/vault-secrets-operator/runs/2160488585)

**Comment by ChipWolf** [comment]
Seems to initialize, some kind of regression though, there's a missing flag ![](https://i.cwlf.uk/NLD5w)

**Comment by ChipWolf** [comment]
Seems to initialize now @ricoberger, some kind of regression though, there's a missing flag ![](https://i.cwlf.uk/NLD5w)

**Comment by ricoberger** [comment]
Hi @ChipWolf, thanks for testing 🙂.

Yes we had to adjust the Helm chart in one of the last version, because of the latest Operator SDK update.

**Comment by ChipWolf** [comment]
Works perfectly @ricoberger

**Comment by ricoberger** [comment]
Hi @ChipWolf, thank you for testing the change 🙂.
